CREATE DATABASE WildBeer;

USE WildBeer;

CREATE TABLE southAmericaBeers(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
path VARCHAR(50) NOT NULL,
description VARCHAR(255) NOT NULL,
unitPrice VARCHAR(255) NOT NULL,
taste VARCHAR(10) NOT NULL,
thirsty VARCHAR(10) NOT NULL,
bitterness VARCHAR(10) NOT NULL,
alcohol VARCHAR(10) NOT NULL,
fermentation VARCHAR(10) NOT NULL,
sixPackPrice VARCHAR(10) NOT NULL,
kegPrice VARCHAR(10) NOT NULL,
country VARCHAR(10) NOT NULL,
cat VARCHAR(10) NOT NULL);
